### ISSUE TITLE
Create a release!!!

### ISSUE THREAD

**Issue by CyberPunkCodes** [ruskid/yii2-csv-importer#13]
Would you please create a release?

Installing your package when ours requires yours, is a PITA.

When you have min stability set to `stable`, as one should in their main production repo, you can not install a package that requires yours because it is `dev-master`.

```
- main project
  |->my package
     \-> your package
```

So to install my package, I have to manually install yours in the main repo first, to force it to accept it. That completely goes against the point of composer. My package should be able to install it's required dependencies (ie: yours) streamlined with one command.

So please, click "Releases", create a release, and tag it `v1.0.0`.

Thanks

**Comment by ruskid** [comment]
Done. thanks
