### ISSUE TITLE
Large CSV file

### ISSUE THREAD

**Issue by ettolo** [ruskid/yii2-csv-importer#2]
Hi,
i'm using this extension and works great!
Now i need to import a 18MBytes file (>100.000 records) and i get the typical 'Out Of Memory' error:
PHP Fatal Error – yii\base\ErrorException
Allowed memory size of 268435456 bytes exhausted 
In my test webserver i coud increase the php memory limit to 2GB and the file is imported but i can't do this in my production server.
I'm using this code:

` 

```
    //Import multiple (Fast but not reliable). Will return number of inserted rows
    $numberRowsAffected = $importer->import(new MultipleImportStrategy([
        'tableName' => $table,
        'configs' => [
            [
                'attribute' => 'first_attribute',
                'value' => function($line) {
```

.....`

Any help?
Thank you!

**Comment by onahkenneth** [comment]
In my view, doing it in batches is more memory efficient. Such as flush imported rows to database after maybe 1000 rows are imported, then continue to the next batch. This will ensure you that run out of memory. I hope it helps

**Comment by ettolo** [comment]
Thank you onahkenneth.. but how to do with this extension? Have you done with it?

**Comment by ruskid** [comment]
I guess you have problems with reading big file and allocating memory? 
You can read less by chunks (as onahkenneth mentioned) specifying **fgetcsvOptions** and **startFromLine** options in **CSVReader**

**Comment by ettolo** [comment]
Thank you ruskid!
