### ISSUE TITLE
No rows affected.

### ISSUE THREAD

**Issue by resting** [ruskid/yii2-csv-importer#3]
I'm trying out this plugin with the following example:

``` php
//Import multiple (Fast but not reliable). Will return number of inserted rows
$numberRowsAffected = $importer->import(new MultipleImportStrategy([
    'tableName' => VendorSwType::tableName(),
    'configs' => [
        [
            'attribute' => 'name',
            'value' => function($line) {
                return $line[1];
            },
            'unique' => true, //Will filter and import unique values only. can by applied for 1+ attributes
        ]
    ],
]));
```

But var_dump of `$numberRowsAffected` is `0`.

This [line](https://github.com/ruskid/yii2-csv-importer/blob/master/CSVReader.php#L76) is suspicious. It is unsetting all the lines.

**Comment by ruskid** [comment]
Sorry for late response, if startFromLine = 1, it will unset the first line (row) in csv.

**Comment by resting** [comment]
@ruskid Thanks. Managed to figure out how it works :)
